export const WISHLIST_GET_IDS = "WISHLIST_GET_IDS";
export const WISHLIST_ADD_PRODUCT = "WISHLIST_ADD_PRODUCT";
export const WISHLIST_REMOVE_PRODUCT = "WISHLIST_REMOVE_PRODUCT";
export const WISHLIST_SET_IDS = "WISHLIST_SET_IDS";
export const WISHLIST_GET_PRODUCTS = "WISHLIST_GET_PRODUCTS";
export const WISHLIST_SET_PRODUCTS = "WISHLIST_SET_PRODUCTS";

export const FEATUREDPRODUCTS_GET_SOURCE = "FEATUREDPRODUCTS_GET_SOURCE";
export const FEATUREDPRODUCTS_SET_SOURCE = "FEATUREDPRODUCTS_SET_SOURCE";
export const FEATUREDPRODUCTS_SET_VISIBLE = "FEATUREDPRODUCTS_SET_VISIBLE";
export const FEATUREDPRODUCTS_HANDLE_MODE = "FEATUREDPRODUCTS_HANDLE_MODE";
