export const WISHLIST_GET_IDS = "WISHLIST_GET_IDS";
export const WISHLIST_ADD_PRODUCT = "WISHLIST_ADD_PRODUCT";
export const WISHLIST_REMOVE_PRODUCT = "WISHLIST_REMOVE_PRODUCT";
export const WISHLIST_SET_IDS = "WISHLIST_SET_IDS";
export const WISHLIST_GET_PRODUCTS = "WISHLIST_GET_PRODUCTS";
export const WISHLIST_SET_PRODUCTS = "WISHLIST_SET_PRODUCTS";
export const WISHLIST_ERROR = "WISHLIST_ERROR";

export const FEATUREDPRODUCTS_GET_SOURCE = "FEATUREDPRODUCTS_GET_SOURCE";
export const FEATUREDPRODUCTS_SET_SOURCE = "FEATUREDPRODUCTS_SET_SOURCE";
export const FEATUREDPRODUCTS_SET_VISIBLE = "FEATUREDPRODUCTS_SET_VISIBLE";
export const FEATUREDPRODUCTS_HANDLE_MODE = "FEATUREDPRODUCTS_HANDLE_MODE";
export const FEATUREDPRODUCTS_APPLY_FILTER = "FEATUREDPRODUCTS_APPLY_FILTER";
export const FEATUREDPRODUCTS_SET_FILTERS = "FEATUREDPRODUCTS_SET_FILTERS";

export const NOTIFICATION_READED = "NOTIFICATION_READED";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSE = "MODAL_CLOSE";

export const DEPARTMENTS_PRODUCTS_SEARCH = "DEPARTMENTS_PRODUCTS_SEARCH";
export const DEPARTMENTS_PRODUCTS_FOCUS = "DEPARTMENTS_PRODUCTS_FOCUS";
export const DEPARTMENTS_PRODUCTS_BLUR = "DEPARTMENTS_PRODUCTS_BLUR";
export const DEPARTMENTS_PRODUCTS_SET = "DEPARTMENTS_PRODUCTS_SET";
export const DEPARTMENTS_PRODUCTS_SELECTED_CHANGED = "DEPARTMENTS_PRODUCTS_SELECTED_CHANGED";