export const WISHLIST_GET_IDS = "WISHLIST_GET_IDS";
export const WISHLIST_ADD_PRODUCT = "WISHLIST_ADD_PRODUCT";
export const WISHLIST_SET_IDS = "WISHLIST_SET_IDS";
export const WISHLIST_GET_PRODUCTS = "WISHLIST_GET_PRODUCTS";
